name: CI

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install backend deps
        working-directory: backend
        run: npm ci --no-audit --fund=false

      - name: Test backend (non-blocking)
        working-directory: backend
        run: npm test || true

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci --no-audit --fund=false

      - name: Lint frontend (non-blocking)
        working-directory: frontend
        run: npm run lint || true

      - name: Build frontend
        working-directory: frontend
        env:
          CI: false
        run: npm run build
